// Give users the following options: Rock, Paper, Scissors.
// Accept random selection input from user
// Generate a random selection of Rock, Paper, or Scissors by computer
// Evaluate outcome of user / computer selections using Rock Paper Scissors Rules:
  // Rock, Rock = Draw. Redo game
  // Rock, Paper = Paper wins
  // Rock, Scissors = Rock wins
  // Paper, Paper = Draw. Redo game
  // Paper, Rock = Paper wins
  // Paper, Scissors = Scissors wins
  // Scissors, Scissors = Draw. Redo game
  // Scissors, Rock = Rock Wins
  // Scissors, Paper = Scissors wins.
// Record “wins” generated by user input
  // Stop at 2 wins
// Record “wins” generated by computer input
  // Stop at 2 wins
// Recognize “stop”
  // winner is determined by user/computer that caused “stop”
// Display message signifying winner
